export  const options = [
    { value: 'matematica', label: 'Matemática' },
    { value: 'fisica', label: 'Física' },
    { value: 'quimica', label: 'Química' },
    { value: 'biologia', label: 'Biología' },
    { value: 'historia', label: 'Historia' },
    { value: 'geografia', label: 'Geografía' },
    { value: 'ingles', label: 'Inglés' },
    { value: 'literatura', label: 'Literatura' },
    { value: 'filosofia', label: 'Filosofía' },
    { value: 'programacion', label: 'Programación' },
    { value: 'calculo', label: 'Cálculo' },
    { value: 'estadistica', label: 'Estadística' },
    { value: 'algebra', label: 'Álgebra' },
    { value: 'economia', label: 'Economía' },
    { value: 'psicologia', label: 'Psicología' },
    { value: 'sociologia', label: 'Sociología' },
    { value: 'derecho', label: 'Derecho' },
    { value: 'marketing', label: 'Marketing' },
    { value: 'administracion', label: 'Administración' },
    { value: 'finanzas', label: 'Finanzas' },
    { value: 'contabilidad', label: 'Contabilidad' },
    { value: 'ingenieria', label: 'Ingeniería' },
    { value: 'medicina', label: 'Medicina' },
    { value: 'arquitectura', label: 'Arquitectura' },
    { value: 'diseño_grafico', label: 'Diseño Gráfico' },
    { value: 'musica', label: 'Música' },
    { value: 'arte', label: 'Arte' },
  ];